name: Call Kalm Deploy Webhook

on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: A job to deploy new Kalm Component
    steps:
      - name: Use Deploy Action
        uses: kalmhq/kalm-deploy-action@v0.0.3
        id: deploy
        with:
          KALM_API_ADDRESS: ${{ secrets.KALM_API_ADDRESS }}
          KALM_DEPLOY_KEY: ${{ secrets.KALM_DEPLOY_KEY }}
          KALM_APP: <application-name>
          KALM_COMPONENT: <component-name>
          KALM_COMPONENT_IMG_TAG: <image-tag>
      - name: output of step deploy
        run: echo 'The callback response was ${{ steps.deploy.outputs.resp }}.'
        
